Fix PHP bug 66019: YYYY-MM-DDTHH is not supported
derickr/timelib pull request #106
Opened 2021-04-07 12:40 UTC by cmb69

2021-04-07 17:00 UTC, derickr requested changes

2021-04-09 12:43 UTC, cmb69 commented on parse_date.re
> +				}
Oh, right. Thanks!

2021-04-09 12:44 UTC, cmb69 commented on tests/c/parse_date.cpp
> +	LONGS_EQUAL(23, t->h);
I've did that now. Could you please check the assertions? I think that `t->tz_abbr` should be `NULL`, but I'm not 100% sure.

2022-04-07 14:33 UTC, closed without merging

2022-05-20 12:27 UTC, derickr commented
Now also merged into PHP (8.1).